idf_component_register(
    SRCS
        "fpm_i2c_guard.c"
        "rtc_rv3028.c"
        "alarm_mgr.c"
        "ms5803.c"
        "ads1115.c"
        "at24c256.c"
        "sfm3300.c"
        "bmp280.c"
    INCLUDE_DIRS 
        "include"
    REQUIRES 
        freertos 
        esp_driver_i2c
    PRIV_REQUIRES 
        esp_driver_ledc
        esp_timer
        storage
)